### config ###

site_name: Documentação do Composer
site_description: "Documentação do Composer [pt-br]"
docs_dir: doc
site_dir: build/2.4
use_directory_urls: false
extra:
    name: Composer
    version: '2.4'
    versions:
        - '2.4'
        - '2.2'
        - '1.10'

### theme ###

theme:
    name: readthedocs
    display_version: true
    prev_next_buttons_location: bottom
    static_templates:
        # config files
        - .nojekyll
        # templates
        - 404.html
        - pesquisar.html

### extensions ###

plugins:
    - search:
        lang: ['pt']

markdown_extensions:
    - attr_list
    - toc:
        permalink: true

### github ###

repo_url: https://github.com/adielcristo/composer-doc-pt-br
edit_uri: edit/2.4/doc/

### navigation ###

nav:
    - index.md
    - Livro:
        - introducao.md
        - uso-basico.md
        - bibliotecas.md
        - 'CLI / Comandos': cli.md
        - esquema.md
        - repositorios.md
        - config.md
        - comunidade.md
    - Artigos:
        - artigos/aliases.md
